### PR TITLE
Update UML for Project Part 4

### PR DESCRIPTION
**Pull request by indragiek**
After everyone's code is in, the UML needs to be updated to account for the changes.

My changes so far:
- Support for adding/removing destinations
- All of the new classes related to the detail screen
- Classes related to the sectioned list adapter

Changes to the UML can be pushed to this branch and they'll appear in this pull request, but before you start making changes make a comment on this pull request to tell others that you're working on it so no one tries to work on it at the same time. Otherwise there will be merge conflicts that are impossible to easily resolve.

### CODE REVIEW

**Comment by indragiek** [comment]
Working on UML changes for @jimmyho899's stuff, don't modify for now.

**Comment by indragiek** [comment]
Done, safe to edit now.

**Comment by mrthegreensky** [comment]
Going to work on this right now.

**Comment by nmrcarroll** [comment]
Updating User class and adding method to expenseclaimlistactivity.

**Comment by indragiek** [comment]
@OriginalFool The commit you pushed didn't update the PNG version of the UML.

**Comment by williums** [comment]
Adding my changes to the UML

**Pull request merged**
