### PR TITLE
Part 5 UML

### PR DESCRIPTION
**Pull request by indragiek**
Mega UML pull request. Push your UML changes here. If you're working on the main UML file (UML.dia) make sure you comment so that other people can wait to make their changes until you finish.

### CODE REVIEW

**Comment by indragiek** [comment]
Working on adding my changes to the main UML file right now, don't edit.

**Comment by indragiek** [comment]
Done my changes, others can edit now.

**Comment by stebenc** [comment]
adding comment stuff right now

**Comment by stebenc** [comment]
done adding comments sections

**Comment by mrthegreensky** [comment]
edited dia file, did not add the new png. completed my part

**Pull request merged**
